language: android
jdk:
    - oraclejdk7
    - oraclejdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA7_HOME
script:
    - ./gradlew clean assemble || ./gradlew clean assemble
